language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - node
# safelist
branches:
  only:
  - master

before_install:
  # yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
